docker_image: harbor-contest.4pd.io/hupenghui/tts:tts_stream_clone_1002
values:
  command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"]
  env:
    - name: max_length
      value: 30
    - name: zh_en
      value: 1
    - name: trunced
      value: 4
  readinessProbe:
    httpGet:
      path: /ready
      port: 80
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 10000
  resources:
    limits:
      cpu: 2
      memory: 8G
      nvidia.com/gpu: 1
    requests:
      cpu: 2
      memory: 8G
      nvidia.com/gpu: 1
