docker_image: harbor-contest.4pd.io/hupenghui/tts:tts_stream_clone_1002
values:
  command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"]
  env:
    - name: max_length
      value: 30
    - name: zh_en
      value: 1.5
    - name: trunced
      value: 2
  readinessProbe:
    httpGet:
      path: /ready
      port: 80
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 1000
  resources:
    limits:
      cpu: 1
      memory: 16G
      nvidia.com/gpu: 1
    requests:
      cpu: 1
      memory: 16G
      nvidia.com/gpu: 1
#  nodeSelector:
#    contest.4pd.io/accelerator: A100-SXM4-80GBvgpu
#A10
#A100-SXM4-80GB
#leaderboard_options:
#  nfs:
#    - name: tts_model
#      srcRelativePath: hupenghui/model/tts_models--multilingual--multi-dataset--xtts_v2
#      mountPoint: /root/model/tts
#      source: ucloud_juicefs
#    - name: zh_model
#      srcRelativePath: hupenghui/model/zh_core_web_sm-3.7.0/zh_core_web_sm/zh_core_web_sm-3.7.0
#      mountPoint: /root/model/zh
#      source: ucloud_juicefs
#    - name: en_model
#      srcRelativePath: hupenghui/model/en_core_web_sm-3.7.1/en_core_web_sm/en_core_web_sm-3.7.1
#      mountPoint: /root/model/en
#      source: ucloud_juicefs
