docker_image: harbor-contest.4pd.io/hupenghui/tts:tts_stream_clone
values:
  command: ["python", "app.py", "--split_length", "40"]
  readinessProbe:
    httpGet:
      path: /ready
      port: 80
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 10000
  resources:
    limits:
      cpu: 1
      memory: 20G
      #nvidia.com/gpu: 1
    requests:
      cpu: 1
      memory: 20G
      #nvidia.com/gpu: 1
#nodeSelector:
#  contest.4pd.io/accelerator: A100-SXM4-80GB